# Generated by Django 6.0.2 on 2026-02-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(help_text='Tiene 10 horas para recibir un libro', max_length=200),
        ),
    ]
